/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ni_niutil_NdkTest */

#ifndef _Included_com_ni_niutil_NdkTest
#define _Included_com_ni_niutil_NdkTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ni_niutil_NdkTest
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ni_niutil_NdkTest_stringFromJNI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
